# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prima.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
@author: galih-hermawan
Github: https://github.com/galihboy/
Web: http://galih.eu
Mail: galih.hermawan@gmail.com
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    #cekPrima = QtCore.pyqtSignal()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 125)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtBilangan = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBilangan.setGeometry(QtCore.QRect(150, 19, 41, 21))
        self.txtBilangan.setObjectName("txtBilangan")
        self.tombolCek = QtWidgets.QPushButton(self.centralwidget)
        self.tombolCek.setGeometry(QtCore.QRect(200, 12, 75, 31))
        self.tombolCek.setObjectName("tombolCek")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 201, 21))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # aksi tombol cek
        self.tombolCek.clicked.connect(self.Periksa)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cek Prima - Galih Hermawan"))
        self.label.setText(_translate("MainWindow", "Masukkan bilangan"))
        self.tombolCek.setText(_translate("MainWindow", "Cek"))
        self.label_2.setText(_translate("MainWindow", "Apakah bilangan prima?"))

    def Periksa(self):
        bil = int(self.txtBilangan.text())
        cek = self.CekPrima(bil)
        if cek:
            teks = "bilangan prima."
        else:
            teks = "bukan bilangan prima"
        self.label_2.setText(teks)
        
    def CekPrima(self, bilangan):
        prima = True
        for i in range(2, bilangan):
            if (bilangan % i == 0):
                prima = False
                break
        return prima

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
