# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prima_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
@author: galih-hermawan
Github: https://github.com/galihboy/
Web: http://galih.eu
Mail: galih.hermawan@gmail.com
"""

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(253, 210)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 51, 16))
        self.label_3.setObjectName("label_3")
        self.txtBawah = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBawah.setGeometry(QtCore.QRect(80, 30, 41, 20))
        self.txtBawah.setObjectName("txtBawah")
        self.txtAtas = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAtas.setGeometry(QtCore.QRect(80, 50, 41, 20))
        self.txtAtas.setObjectName("txtAtas")
        self.txtHasil = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtHasil.setGeometry(QtCore.QRect(10, 110, 231, 51))
        self.txtHasil.setObjectName("txtHasil")
        self.txtHasil.verticalScrollBar()
        self.tombolPeriksa = QtWidgets.QPushButton(self.centralwidget)
        self.tombolPeriksa.setGeometry(QtCore.QRect(160, 40, 75, 31))
        self.tombolPeriksa.setAutoDefault(False)
        self.tombolPeriksa.setDefault(False)
        self.tombolPeriksa.setFlat(False)
        self.tombolPeriksa.setObjectName("tombolPeriksa")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 253, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # aksi tombol cek
        self.tombolPeriksa.clicked.connect(self.Periksa)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "List Prima - Galih Hermawan"))
        self.label.setText(_translate("MainWindow", "Periksa bilangan prima antara:"))
        self.label_2.setText(_translate("MainWindow", "Nilai min:"))
        self.label_3.setText(_translate("MainWindow", "Nilai maks:"))
        self.txtBawah.setText(_translate("MainWindow", "2"))
        self.txtAtas.setText(_translate("MainWindow", "10"))
        self.tombolPeriksa.setText(_translate("MainWindow", "Periksa"))
        self.label_4.setText(_translate("MainWindow", "Hasil:"))
        
    def CekPrima(self, bilangan):
        prima = True
        for i in range(2, bilangan):
            if (bilangan % i == 0):
                prima = False
                break
        return prima
    
    def Periksa(self):
        batasBawah = int(self.txtBawah.text())
        batasAtas = int(self.txtAtas.text())
        jml = 0
        teks = ""
        self.txtHasil.clear()
        for bil in range(batasBawah, batasAtas+1):
            if self.CekPrima(bil):
                teks = teks + ", " + str(bil)
                jml += 1
        teks = teks[2:]
        if jml==0: teks = "bilangan prima tidak ditemukan"
        self.txtHasil.insertPlainText(teks)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
